config/routes.rb
Rails.application.routes.draw do
    resources :candidates do
    collection {post :import}
    end
    resources :notes do
    collection {post :import}
    end

  root to: "candidates#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    has_many :note
    require 'csv'  
    

    def self.import(file)
        CSV.foreach(file.path, { encoding: "UTF-8", headers: true, header_converters: :symbol, converters: :all}) do |row|
            Candidate.create! row.to_hash
        end
    end

end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :candidate
    require 'csv'  
    
    
    def self.import(file)
        CSV.foreach(file.path, { encoding: "UTF-8", headers: true, header_converters: :symbol, converters: :all}) do |row|
            Note.create! row.to_hash
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end

  def import
    Candidate.import(params[:file])
    redirect_to root_url, notice: "Activity Data imported"
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def import
    Note.import(params[:file])
    redirect_to notes_url, notice: "Activity Data imported"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/candidates/_header.html.erb
<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <%=link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to 'Import CSV 1', candidates_path%></li>
        <li><%=link_to 'Import CSV 2', notes_path%></li>
          </ul>
    </div>
  </div>
</nav>

app/views/candidates/index.html.erb
<div id="main-container" class="container">
    <div class="row">
        <div class="col-md-10">
        <h1><p class="text-primary">Candidates Table</p></h1>
        <%= flash[:notice] %>
        <table>
            <thead>
                <th>Name</th>
                <th>E-mail</th>
                <th>Phone</th>
                <th>Job</th>
                <th>Created_at</th>
            </thead>
            <tbody>
                <% @candidates.order("name asc").each do |candidate| %>
                    <tr>
                        <td><%= candidate.name %></td>
                        <td><%= candidate.email %></td>
                        <td><%= candidate.phone %></td>
                        <td><%= candidate.job %></td>
                        <td><%= candidate.created_at %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>

<div>
 <div id="main-container" class="container">
    <div class="row">
        <div class="col-md-3">

            <h4> Import data with candidates! </h4>
                <%= form_tag import_candidates_path, multipart: true do %>
                <%= file_field_tag :file %>
         </div>
                <div class="col-md-3">
                <%= submit_tag "Import CSV", class: 'btn btn-primary' %>
                <% end %> 
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskImport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'candidates/header' %>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<div id="main-container" class="container">
    <div class="row">
        <div class="col-md-10">
        <h1><p class="text-primary">Notes Table</p></h1>
        <%= flash[:notice] %>
        <span class="border border-success">
        <table>
            <thead>
                <th>E-mail</th>
                <th>Note</th>
            </thead>
            <tbody>
                <% @notes.order("email asc").each do |note| %>
                    <tr>
                        <td><%= note.email %></td>
                        <td><%= note.note %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        </span>
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>
<div>
 <div id="main-container" class="container">
    <div class="row">
        <div class="col-md-3">

            <h4> Import data with notes! </h4>
                <%= form_tag import_notes_path, multipart: true do %>
                <%= file_field_tag :file %>
         </div>
                <div class="col-md-3">
                <%= submit_tag "Import CSV", class: 'btn btn-primary' %>
                <% end %> 
                </div>
        </div>
    </div>
</div>